### PR TITLE
Add golang golang.org/x/crypto/ssh

### PR DESCRIPTION
**Pull request by jnewbigin**

### CODE REVIEW

**Comment by fingolfin** [comment]
Thanks! However, this is not going to work: You have added a .yml file, not an .md file. I suggest taking a look at the other files in the directory to see how it works. Did you try it locally to verify the result looks right (I.e. by running jekyll to build the site) ?

**Comment by jnewbigin** [comment]
Ahh, I guess I'll have to look a bit deeper. I'll try it out when I get a bit more time.

**Comment by fingolfin** [comment]
Sure. Well, basically, you need to change the file suffix, and add one boiler plate line `---` at the top and bottom each. Just as in the other files in the `_impls` dir. That should be all. But of course, as always with software projects, I would recommend _testing_ any changes before submitting them. So, `gem install jekyll && jekyll serve` inside your ssh-comparision clone, then visit `localhost:4000` ...

**Comment by fingolfin** [comment]
Any news on this?

**Comment by jnewbigin** [comment]
Hi,
I have Cleaned it up but not pushed it. I'll try and find time to finish it
off this week
John

**Comment by fingolfin** [comment]
Ping?

**Pull request closed without merging**
