### PR TITLE
Updated SmartFTP

### PR DESCRIPTION
**Pull request by matbech**
updated public key algorithms.

### CODE REVIEW

**Comment by fingolfin** [comment]
Are you sure about this?

I can't run SmartFTP right now (don't have my HD with the Windows virtual machine at hand), but I downloaded the installer and extracted it (via 7zip), and then used the good old `strings` command. That gave hits for x509v3-sign-\* but NOT for x509v3-ssh-*

**Comment by fingolfin** [comment]
Note that the `x509v3-sign-*` algos were specified in a draft of the SSH 2 protocol, but apparently removed from the final version. See e.g. https://tools.ietf.org/html/draft-ietf-secsh-transport-16

**Comment by matbech** [comment]
Yes and I believe petrov still supports them in his patch:
http://roumenpetrov.info/openssh/

But they have been superseded with https://tools.ietf.org/html/rfc6187

That is the reason they have been replaced in SmartFTP with the one from RFC 6187.

**Comment by fingolfin** [comment]
But the SmartFTPI downloaded yesterday definitely did not (yet) have this change. Which means this pull request is again missing a version increment (assuming that since yesterday, a release of SmartFTP happened which has this change in effect).

By the way, note the curious fact that SmartFTP seems to be the _only_ implementaiton of RFC 6187, at least in this comparison :-). All other implementations use the old names.

**Comment by matbech** [comment]
My version of SmartFTP is always a bit ahead of the public release :-) The latest version (Build 2201) does include the change.

**Comment by fingolfin** [comment]
... but doesn't mention this in its changelog _sigh_. OTOH, https://www.smartftp.com/changelog/2 does mention such a change (but does not state whether the old method was replaced, as your change here suggests; or whether the new method was added in parallel to the old method. (The latter would make some sense, to provide interoperability with implementations still using the old name).

So, do you know for certain that this was a _replacement_?

**Comment by fingolfin** [comment]
@matbech So you told me via email that you are the author of SmartFTP. Great. Then that confirms the correctness of the change -- but the fact remains that the change in this PR is incomplete, because it suggests that the change affects version 7.0.2199, which of course is not correct. So I would appreciate if you could correct that, then we can merge this PR. Or alternatively, I am happy to perform the required change mysefl.

**Comment by fingolfin** [comment]
Thanks!

**Pull request merged**
