### PR TITLE
smartftp: removed dsa

### PR DESCRIPTION
**Pull request by matbech**
Removed support for DSA keys

### CODE REVIEW

**Comment by fingolfin** [comment]
Thanks!
So support for dsa was removed, but the version did not change? So was the original entry simply wrong? Or does this PR forget to update the version?

**Comment by matbech** [comment]
The version has been updated now.

**Comment by fingolfin** [comment]
Awesome, thanks. Could you perhaps squash this into one commit?

**Comment by fingolfin** [comment]
I just used GitHubs squash feature. Thank you for your patch, and sorry for the delay in merging.

**Pull request merged**
